### ISSUE TITLE
Random Issue, not sure what its about.

### ISSUE THREAD

**Issue by tylerlazenby** [Blarc/gitlab-template-lint-plugin#124]
I am getting this exception being raised

java.nio.file.InvalidPathException: Illegal char <?> at index 32: /What's New in Material Theme UI?
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at com.github.blarc.gitlab.template.lint.plugin.GitlabLintUtils.matchesGlobs(GitlabLintUtils.kt:43)
	at com.github.blarc.gitlab.template.lint.plugin.GitlabLintUtils.matchesInclusionGlobs(GitlabLintUtils.kt:31)
	at com.github.blarc.gitlab.template.lint.plugin.GitlabLintUtils.isGitlabYaml(GitlabLintUtils.kt:17)
	at com.github.blarc.gitlab.template.lint.plugin.language.GitlabYamlFileTypeOverrider.getOverriddenFileType(GitlabYamlFileTypeOverrider.kt:10)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.lambda$getFileTypeByFile$16(FileTypeManagerImpl.java:745)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.kt:57)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.kt:57)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:745)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:692)
	at com.intellij.openapi.vfs.VirtualFile.getFileType(VirtualFile.java:356)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorProvider.isTextFile(TextEditorProvider.java:237)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorProvider.accept(TextEditorProvider.java:65)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.checkProvider(FileEditorProviderManagerImpl.kt:77)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.getProviderList$lambda$2$lambda$1(FileEditorProviderManagerImpl.kt:94)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:891)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.getProviderList(FileEditorProviderManagerImpl.kt:93)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.canOpenFile(FileEditorManagerEx.kt:99)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4$intellij_platform_ide_impl(FileEditorManagerImpl.kt:958)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2$lambda$22(FileEditorManagerImpl.kt:900)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.kt:899)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFile(FileEditorManagerImpl.kt:798)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.kt:131)
	at com.intellij.openapi.fileEditor.impl.HTMLEditorProvider$Companion.openEditor(HTMLEditorProvider.kt:50)
	at com.intellij.openapi.fileEditor.impl.HTMLEditorProvider$Companion.openEditor(HTMLEditorProvider.kt:43)
	at com.mallowigi.idea.notifications.MTWhatsNewAction$Companion.openWhatsNewFile(MTWhatsNewAction.kt:111)
	at com.mallowigi.idea.MTUpdatesComponent.projectOpened$lambda$0(MTUpdatesComponent.kt:72)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by Blarc** [comment]
A fix was released under version 1.13.1. You can wait for JetBrains to approve version 1.13.1 or download it manually from https://github.com/Blarc/gitlab-template-lint-plugin/releases/tag/v1.13.1 and installing it following these [steps](https://github.com/Blarc/gitlab-template-lint-plugin#installation-from-zip).

Thanks for reporting back. :raised_hands:
