### ISSUE TITLE
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())

### ISSUE THREAD

**Issue by comanl** [Blarc/gitlab-template-lint-plugin#140]
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[ApplicationImpl pooled thread 89,4,main] 1936836381 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1333007738
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1002)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.evaluateValidity(FileManagerImpl.java:596)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.evaluateValidity(FileManagerImpl.java:592)
	at com.intellij.psi.impl.source.PsiFileImpl.isValid(PsiFileImpl.java:163)
	at com.intellij.psi.impl.source.PsiFileImpl.getText(PsiFileImpl.java:305)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.middleware.LintContext.lintContent(LintContext.kt:90)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.middleware.LintContext.invoke(LintContext.kt:32)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline.next(Pipeline.kt:47)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline.access$next(Pipeline.kt:13)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline$next$1.invoke(Pipeline.kt:48)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline$next$1.invoke(Pipeline.kt:47)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.middleware.ResolveRemoteId.invoke(ResolveRemoteId.kt:24)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline.next(Pipeline.kt:47)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline.access$next(Pipeline.kt:13)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline$next$1.invoke(Pipeline.kt:48)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline$next$1.invoke(Pipeline.kt:47)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.middleware.RecordHit.invoke(RecordHit.kt:15)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline.next(Pipeline.kt:47)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline.access$next(Pipeline.kt:13)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline$next$1.invoke(Pipeline.kt:48)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline$next$1.invoke(Pipeline.kt:47)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.middleware.ShowSupportNotification.invoke(ShowSupportNotification.kt:17)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline.next(Pipeline.kt:47)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline.access$next(Pipeline.kt:13)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline$next$1.invoke(Pipeline.kt:48)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline$next$1.invoke(Pipeline.kt:47)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.middleware.ResolveGitlabToken.invoke(ResolveGitlabToken.kt:22)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline.next(Pipeline.kt:47)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline.access$next(Pipeline.kt:13)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline$next$1.invoke(Pipeline.kt:48)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline$next$1.invoke(Pipeline.kt:47)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.middleware.ResolveContext.invoke(ResolveContext.kt:53)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline.next(Pipeline.kt:47)
	at com.github.blarc.gitlab.template.lint.plugin.pipeline.Pipeline.accept(Pipeline.kt:38)
	at com.github.blarc.gitlab.template.lint.plugin.GitlabLintRunnerKt$lint$$inlined$runBackgroundableTask$default$1.run(progress.kt:42)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by comanl** [comment]
IntelliJ IDEA 2023.1.4 (Ultimate Edition)
Build #IU-231.9225.16, built on July 12, 2023


Runtime version: 17.0.7+10-b829.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    scala.erase.compiler.process.jdk.once=false
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (231.9225.16)
    com.intellij.lang.puppet (231.8109.91)
    Batch Scripts Support (1.0.13)
    com.intellij.aqua.selenium (231.8109.91)
    com.perl5 (2023.1.2)
    org.intellij.plugins.hcl (231.8109.91)
    com.intellij.plugins.watcher (231.8109.91)
    com.intellij.ideolog (222.1.0.0)
    ir.msdehghan.plugins.ansible (0.92)
    org.jetbrains.plugins.go (231.9225.16)
    org.jetbrains.plugins.ruby (231.9225.16)
    com.intellij.kubernetes (231.9011.4)
    com.intellij.guice (231.8109.90)
    com.jetbrains.jax.ws (231.8109.90)
    com.intellij.aqua (231.9225.5)
    org.jetbrains.kotlin (231-1.9.0-release-358-IJ8770.65)
    com.intellij.javaee.batch (231.8109.90)
    com.dmarcotte.handlebars (231.8770.3)
    com.intellij.tide (231.9161.14)
    org.asciidoctor.intellij.asciidoc (0.38.20)
    Pythonid (231.9225.16)
    org.intellij.scala (2023.1.19)
    com.intellij.bigdatatools (231.9011.34)
    com.github.blarc.gitlab-template-lint-plugin (1.13.2)
    com.carbonblack.intellij.rpmspec (2.1.0)
    com.intellij.spring.batch (231.8770.17)
    org.sonarlint.idea (8.4.0.73538)
    com.baomidou.plugin.idea.mybatisx (1.5.5)
    com.jetbrains.php (231.9225.16)
    ru.adelf.idea.dotenv (2023.1)

Kotlin: 231-1.9.0-release-358-IJ8770.65

**Comment by rfalke-rtl** [comment]
I'm also seeing this:
```
   Unhandled exception in [CoroutineName(com.intellij.openapi.fileEditor.impl.PsiAwareFileEditorManagerImpl), StandaloneCoroutine{Cancelling}@52ffffa5, Dispatchers.Default]
   
   com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[DefaultDispatcher-worker-8,4,main] 199243217 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1664839308
	at com.intellij.openapi.application.impl.ApplicationImpl.createThreadAccessException(ApplicationImpl.java:1083)
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1078)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1066)
	at com.intellij.openapi.editor.impl.EditorImpl.assertIsDispatchThread(EditorImpl.java:3414)
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:365)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createMainEditor(EditorFactoryImpl.java:220)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl$Companion.createTextEditor(TextEditorImpl.kt:94)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.<init>(PsiAwareTextEditorImpl.kt:47)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.createEditor(PsiAwareTextEditorProvider.kt:28)
	at com.github.blarc.gitlab.template.lint.plugin.providers.EditorWithMergedPreview$Companion.create(GitlabLintEditorProvider.kt:43)
	at com.github.blarc.gitlab.template.lint.plugin.providers.GitlabLintEditorProvider.createEditor(GitlabLintEditorProvider.kt:25)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$dumbModeFinished$fileToNewProviders$2$1$1$1.invoke(FileEditorManagerImpl.kt:437)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$dumbModeFinished$fileToNewProviders$2$1$1$1.invoke(FileEditorManagerImpl.kt:437)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:105)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:41)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:39)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:37)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:34)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:76)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:63)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:42)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:38)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:58)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:25)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.dumbModeFinished(FileEditorManagerImpl.kt:437)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$dumbModeFinished(FileEditorManagerImpl.kt:121)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$dumbModeFinished$1.invokeSuspend(FileEditorManagerImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(com.intellij.openapi.fileEditor.impl.PsiAwareFileEditorManagerImpl), StandaloneCoroutine{Cancelled}@52ffffa5, Dispatchers.Default]
```

IntelliJ:
```
IntelliJ IDEA 2023.2.5 (Ultimate Edition)
Build #IU-232.10227.8, built on November 9, 2023
Licensed to ...
Runtime version: 17.0.9+7-b1000.46 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6
GC: G1 Young Generation, G1 Old Generation
Memory: 6048M
Cores: 12
Metal Rendering is ON
Registry:
    debugger.watches.in.variables=false

Non-Bundled Plugins:
    name.kropp.intellij.makefile (232.8660.88)
    com.intellij.grazie.pro (0.3.265)
    com.github.blarc.gitlab-template-lint-plugin (1.13.2)
    org.intellij.plugins.hcl (232.8660.88)
    com.jetbrains.plugins.ini4idea (232.10227.13)
    org.jetbrains.kotlin (232-1.9.20-release-507-IJ10072.27)
    com.jetbrains.php (232.10227.13)
    com.intellij.lang.jsgraphql (4.0.2)
    Pythonid (232.10227.8)
    com.nekofar.milad.intellij.nestjs (1.2.22)
    com.intellij.kubernetes (232.10203.2)
    org.jetbrains.plugins.go-template (232.9921.89)

Kotlin: 232-1.9.20-release-507-IJ10072.27
```
