### ISSUE TITLE
Access is allowed from event dispatch thread only

### ISSUE THREAD

**Issue by DidierLoiseau** [Blarc/gitlab-template-lint-plugin#32]
I regularly get the following exception from the GitLab Template Lint plugin in the IDE Internal Errors:
```
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[ApplicationImpl pooled thread 380,4,main] 168861003
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 332416601
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1110)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1093)
	at com.intellij.dvcs.DvcsUtil.guessCurrentRepositoryQuick(DvcsUtil.java:278)
	at com.github.blarc.gitlab.template.lint.plugin.GitlabLintRunner.run(GitlabLintRunner.kt:30)
	at com.github.blarc.gitlab.template.lint.plugin.inspections.GitlabLintInspector$buildVisitor$1$visitFile$$inlined$runBackgroundableTask$default$1.run(progress.kt:42)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by qayshp** [comment]
Same here, using `2022.2.1` version of idea.

Looking at [this stackoverflow answer](https://stackoverflow.com/questions/54826606/intellij-plugin-access-is-allowed-from-event-dispatch-thread-only) it seems to me like this might be fixable by something like replacing `fun run(content: String, filePath: String){` with `fun run(content: String, filePath: String) = ApplicationManager.getApplication().invokeLater {` and of course an `import com.intellij.openapi.application.ApplicationManager`

I could absolutely be wrong, and haven't tested this 🤷. If I get a plugin dev env setup later, I'll try this.

Also, looking at the branches in this repo, the maintainer is working on some larger refactors, so this may be something they plan to or already have addressed in that.

**Comment by Blarc** [comment]
Could you please check if this exception still occurs to you in version 1.0.1?

**Comment by DidierLoiseau** [comment]
I don’t think I have had it again (with 1.1.0).
